import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{createClient}from'@supabase/supabase-js';
import{Users,Store,Package,ShoppingCart,LayoutDashboard,LogOut,Search,TrendingUp,Clock,RefreshCw,AlertTriangle,Mail,Phone}from'lucide-react';
import{ResponsiveContainer,AreaChart,Area,XAxis,YAxis,Tooltip,CartesianGrid}from'recharts';
import'./styles.css';
const URL='https://sqvtimbmpiwlnikipicp.supabase.co';
const KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxdnRpbWJtcGl3bG5pa2lwaWNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0NDgwMTksImV4cCI6MjA3NjAyNDAxOX0.UPe-OQnA0FJtPS5P59cahE3BPcdVfUHki6SG0WKPdpU';
const db=createClient(URL,KEY),PASS='49ecfb0d0fb30e9353a4e05f5316246bb456947c6ec87ad8d396f4366d8a3ccf';
const nav=[['overview','نظرة عامة',LayoutDashboard],['users','المستخدمون',Users],['stores','المتاجر',Store],['products','المنتجات',Package],['orders','الطلبات والمعاملات',ShoppingCart]];
const fmt=n=>new Intl.NumberFormat('ar-DZ').format(Number(n)||0),date=v=>v?new Date(v).toLocaleDateString('ar-DZ'):'—';
async function hash(s){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function Login({done}){const[p,setP]=useState(''),[err,setErr]=useState(''),[busy,setBusy]=useState(false);return <form className="login" onSubmit={async e=>{e.preventDefault();setBusy(true);setErr('');if(await hash(p)===PASS){sessionStorage.setItem('kilix_employee','1');done()}else setErr('الرمز السري غير صحيح');setBusy(false)}}><div className="loginCard"><div className="logo"><b>K</b><span>Kilix</span></div><h1>لوحة الموظفين</h1><p>الوصول مخصص لفريق Kilix</p><input autoFocus type="password" value={p} onChange={e=>setP(e.target.value)} placeholder="الرمز السري"/><button disabled={busy}>{busy?'جارٍ التحقق…':'دخول'}</button>{err&&<small className="err">{err}</small>}</div></form>}
function App(){const[auth,setAuth]=useState(sessionStorage.getItem('kilix_employee')==='1'),[page,setPage]=useState('overview'),[data,setData]=useState({users:[],stores:[],products:[],orders:[]}),[problems,setProblems]=useState([]),[loading,setLoading]=useState(false),[q,setQ]=useState('');useEffect(()=>{if(auth)load()},[auth]);
async function load(){setLoading(true);const names=['users','stores','products','orders'],out={},bad=[];await Promise.all(names.map(async t=>{const{data,error}=await db.from(t).select('*').order('created_at',{ascending:false});if(error)bad.push(t);else out[t]=data||[]}));setData(d=>({...d,...out}));setProblems(bad);setLoading(false)}
const s=useMemo(()=>{const u=data.users,ago=n=>Date.now()-n*864e5;return{users:u.length,week:u.filter(x=>x.created_at&&new Date(x.created_at).getTime()>=ago(7)).length,month:u.filter(x=>x.created_at&&new Date(x.created_at).getTime()>=ago(30)).length,stores:data.stores.length,products:data.products.length,orders:data.orders.length,withStore:u.filter(x=>x.has_store).length,active:u.filter(x=>x.is_active!==false).length}},[data]);
if(!auth)return <Login done={()=>setAuth(true)}/>;const source=page==='users'?data.users:page==='stores'?data.stores:page==='products'?data.products:data.orders,rows=source.filter(x=>JSON.stringify(x).toLowerCase().includes(q.toLowerCase())).slice(0,200);function logout(){sessionStorage.removeItem('kilix_employee');setAuth(false)}return <div className="app"><aside><div className="brand"><span>K</span><b>Kilix</b></div>{nav.map(([id,label,I])=><button key={id} className={page===id?'active':''} onClick={()=>{setPage(id);setQ('')}}><I size={19}/>{label}</button>)}<div className="sideBottom"><button onClick={load}><RefreshCw size={18}/>تحديث البيانات</button><button onClick={logout}><LogOut size={18}/>خروج</button></div></aside><main><header><div><h1>{nav.find(x=>x[0]===page)[1]}</h1><span className="muted">إدارة ومتابعة منصة Kilix</span></div><span className="live">● مباشر</span></header>{problems.length>0&&<div className="warning"><AlertTriangle size={19}/><div><b>الواجهة تعمل لكن صلاحية قراءة بعض الجداول تحتاج ضبطًا</b><p>سنربط صلاحيات الموظفين الآمنة في المرحلة التالية. لا نعرض بيانات وهمية.</p></div></div>}{page==='overview'?<Overview s={s} users={data.users} loading={loading}/>:<Table page={page} rows={rows} q={q} setQ={setQ}/>}</main></div>}
function Overview({s,users,loading}){const chart=Array.from({length:7},(_,i)=>{const d=new Date(Date.now()-(6-i)*864e5);return{name:d.toLocaleDateString('ar-DZ',{weekday:'short'}),value:users.filter(x=>x.created_at&&new Date(x.created_at).toDateString()===d.toDateString()).length}});return <><section className="cards"><Card I={Users} t="إجمالي المستخدمين" v={s.users} x={`+${s.week} آخر 7 أيام`}/><Card I={TrendingUp} t="مستخدمون جدد" v={s.month} x="آخر 30 يومًا"/><Card I={Store} t="المتاجر" v={s.stores} x={`${s.withStore} حسابًا يملك متجرًا`}/><Card I={ShoppingCart} t="المعاملات" v={s.orders} x="إجمالي الطلبات"/></section><section className="grid"><div className="panel"><div className="panelHead"><div><h2>نمو المستخدمين</h2><p>آخر 7 أيام</p></div><TrendingUp/></div><ResponsiveContainer width="100%" height={280}><AreaChart data={chart}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name"/><YAxis allowDecimals={false}/><Tooltip/><Area type="monotone" dataKey="value" stroke="#FF6B00" fill="#FFF1E6" strokeWidth={3}/></AreaChart></ResponsiveContainer></div><div className="panel"><div className="panelHead"><div><h2>حالة المنصة</h2><p>{loading?'جارٍ التحميل…':'بيانات مباشرة'}</p></div></div><Metric t="حسابات نشطة" v={s.active}/><Metric t="منتجات منشورة" v={s.products}/><Metric t="حسابات بدون متجر" v={s.users-s.withStore}/><Metric t="جدد هذا الشهر" v={s.month}/></div></section><section className="panel notice"><Clock/><div><b>وقت الاستخدام</b><p>لن نعرض ساعات وهمية. قاعدة البيانات الحالية لا تسجل جلسات بداية/نهاية كافية لحساب الساعات بدقة.</p></div></section></>}
function Card({I,t,v,x}){return <div className="stat"><div className="statIcon"><I size={21}/></div><div><span>{t}</span><strong>{fmt(v)}</strong><small>{x}</small></div></div>};function Metric({t,v}){return <div className="metric"><span>{t}</span><b>{fmt(v)}</b></div>}
function Table({page,rows,q,setQ}){const title=page==='users'?'حسابات العملاء':page==='stores'?'المتاجر':page==='products'?'المنتجات':'الطلبات والمعاملات';return <section className="panel listPanel"><div className="toolbar"><div><h2>{title}</h2><p>{fmt(rows.length)} سجل معروض</p></div><div className="search"><Search size={17}/><input placeholder="بحث في البيانات…" value={q} onChange={e=>setQ(e.target.value)}/></div></div><div className="tableWrap"><table><thead><tr>{page==='users'?<><th>العميل</th><th>البريد</th><th>الهاتف</th><th>نوع الحساب</th><th>متجر</th><th>التسجيل</th></>:page==='stores'?<><th>المتجر</th><th>المالك</th><th>نوع التاجر</th><th>التقييم</th><th>المتابعون</th></>:page==='products'?<><th>المنتج</th><th>المتجر</th><th>السعر</th><th>التصنيف</th><th>الحالة</th></>:<><th>العميل</th><th>المنتج</th><th>الهاتف</th><th>الإجمالي</th><th>الحالة</th><th>التاريخ</th></>}</tr></thead><tbody>{rows.map(x=><tr key={x.auth_id||x.id}>{page==='users'?<><td><b>{[x.first_name,x.last_name].filter(Boolean).join(' ')||'—'}</b><small>{x.user_code||''}</small></td><td><span className="contact"><Mail size={13}/>{x.email||'—'}</span></td><td><span className="contact"><Phone size={13}/>{x.phone||'—'}</span></td><td>{x.account_type||'—'}</td><td>{x.has_store?'نعم':'لا'}</td><td>{date(x.created_at)}</td></>:page==='stores'?<><td><b>{x.store_name||'—'}</b><small>{x.store_code||''}</small></td><td>{x.owner_id||'—'}</td><td>{x.merchant_type||'—'}</td><td>{Number(x.average_rating||0).toFixed(1)}</td><td>{fmt(x.followers_count)}</td></>:page==='products'?<><td><b>{x.title||'—'}</b></td><td>{x.store_id||'—'}</td><td>{fmt(x.price)} دج</td><td>{x.category||'—'}</td><td><span className={x.is_active?'pill good':'pill'}>{x.is_active?'نشط':'متوقف'}</span></td></>:<><td>{x.customer_name||x.email||'—'}</td><td>{x.product_title||'—'}</td><td>{x.phone||'—'}</td><td>{fmt(x.total_price)} {x.currency||'دج'}</td><td>{x.status||'—'}</td><td>{date(x.created_at)}</td></>}</tr>)}</tbody></table></div></section>}
createRoot(document.getElementById('root')).render(<App/>);
